/**:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_nn_type: spatial
      i_pipeline_type: RGBD
    # QoS settings optimized for wireless communication
    rgb:
      i_qos_reliability: "best_effort"
      i_qos_durability: "volatile"
      i_qos_history_depth: 4
      i_qos_lifespan: 0.15
    stereo:
      i_qos_reliability: "best_effort"
      i_qos_durability: "volatile"
      i_qos_history_depth: 4
      i_qos_lifespan: 0.15
    left:
      i_qos_reliability: "best_effort"
      i_qos_durability: "volatile"
      i_qos_history_depth: 4
      i_qos_lifespan: 0.15
    right:
      i_qos_reliability: "best_effort"
      i_qos_durability: "volatile"
      i_qos_history_depth: 4
      i_qos_lifespan: 0.15
    nn:
      i_nn_config_path: depthai_ros_driver/mobilenet